apiVersion: v1
kind: Namespace
metadata:
  name: mcp
  labels:
    name: mcp
    environment: development
    app.kubernetes.io/part-of: commerce-intelligence-platform
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mcp-quota
  namespace: mcp
spec:
  hard:
    # Compute resources
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    
    # Storage resources
    requests.storage: 100Gi
    
    # Object count limits
    pods: "100"
    services: "50"
    configmaps: "50"
    secrets: "50"
    persistentvolumeclaims: "30"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mcp-limits
  namespace: mcp
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container