apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-admin
  namespace: mcp
  labels:
    app.kubernetes.io/part-of: commerce-intelligence-platform
    app.kubernetes.io/component: admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-api-gateway
  namespace: mcp
  labels:
    app.kubernetes.io/part-of: commerce-intelligence-platform
    app.kubernetes.io/component: api-gateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-model-registry
  namespace: mcp
  labels:
    app.kubernetes.io/part-of: commerce-intelligence-platform
    app.kubernetes.io/component: model-registry
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-model-runner
  namespace: mcp
  labels:
    app.kubernetes.io/part-of: commerce-intelligence-platform
    app.kubernetes.io/component: model-runner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-orchestration
  namespace: mcp
  labels:
    app.kubernetes.io/part-of: commerce-intelligence-platform
    app.kubernetes.io/component: orchestration
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-data-access
  namespace: mcp
  labels:
    app.kubernetes.io/part-of: commerce-intelligence-platform
    app.kubernetes.io/component: data-access
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-monitoring
  namespace: mcp
  labels:
    app.kubernetes.io/part-of: commerce-intelligence-platform
    app.kubernetes.io/component: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mcp-admin-role
  namespace: mcp
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mcp-admin-binding
  namespace: mcp
subjects:
- kind: ServiceAccount
  name: mcp-admin
  namespace: mcp
roleRef:
  kind: Role
  name: mcp-admin-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mcp-service-role
  namespace: mcp
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mcp-service-binding
  namespace: mcp
subjects:
- kind: ServiceAccount
  name: mcp-api-gateway
  namespace: mcp
- kind: ServiceAccount
  name: mcp-model-registry
  namespace: mcp
- kind: ServiceAccount
  name: mcp-model-runner
  namespace: mcp
- kind: ServiceAccount
  name: mcp-orchestration
  namespace: mcp
- kind: ServiceAccount
  name: mcp-data-access
  namespace: mcp
- kind: ServiceAccount
  name: mcp-monitoring
  namespace: mcp
roleRef:
  kind: Role
  name: mcp-service-role
  apiGroup: rbac.authorization.k8s.io